export const FILLINGS = [
	{
		_id: '643d69a5c3f7b9001cfa093e',
		name: 'Филе Люминесцентного тетраодонтимформа',
		type: 'main',
		proteins: 44,
		fat: 26,
		carbohydrates: 85,
		calories: 643,
		price: 988,
		image: 'https://code.s3.yandex.net/react/code/meat-03.png',
		image_mobile: 'https://code.s3.yandex.net/react/code/meat-03-mobile.png',
		image_large: 'https://code.s3.yandex.net/react/code/meat-03-large.png',
		__v: 0,
	},
	{
		_id: '643d69a5c3f7b9001cfa0942',
		name: 'Соус Spicy-X',
		type: 'sauce',
		proteins: 30,
		fat: 20,
		carbohydrates: 40,
		calories: 30,
		price: 90,
		image: 'https://code.s3.yandex.net/react/code/sauce-02.png',
		image_mobile: 'https://code.s3.yandex.net/react/code/sauce-02-mobile.png',
		image_large: 'https://code.s3.yandex.net/react/code/sauce-02-large.png',
		__v: 0,
	},
	{
		_id: '643d69a5c3f7b9001cfa093f',
		name: 'Мясо бессмертных моллюсков Protostomia',
		type: 'main',
		proteins: 433,
		fat: 244,
		carbohydrates: 33,
		calories: 420,
		price: 1337,
		image: 'https://code.s3.yandex.net/react/code/meat-02.png',
		image_mobile: 'https://code.s3.yandex.net/react/code/meat-02-mobile.png',
		image_large: 'https://code.s3.yandex.net/react/code/meat-02-large.png',
		__v: 0,
	},
	{
		_id: '643d69a5c3f7b9001cfa0940',
		name: 'Говяжий метеорит (отбивная)',
		type: 'main',
		proteins: 800,
		fat: 800,
		carbohydrates: 300,
		calories: 2674,
		price: 3000,
		image: 'https://code.s3.yandex.net/react/code/meat-04.png',
		image_mobile: 'https://code.s3.yandex.net/react/code/meat-04-mobile.png',
		image_large: 'https://code.s3.yandex.net/react/code/meat-04-large.png',
		__v: 0,
	},
	{
		_id: '643d69a5c3f7b9001cfa093d',
		name: 'Флюоресцентная булка R2-D3',
		type: 'bun',
		proteins: 44,
		fat: 26,
		carbohydrates: 85,
		calories: 643,
		price: 988,
		image: 'https://code.s3.yandex.net/react/code/bun-01.png',
		image_mobile: 'https://code.s3.yandex.net/react/code/bun-01-mobile.png',
		image_large: 'https://code.s3.yandex.net/react/code/bun-01-large.png',
		__v: 0,
	},
	{
		_id: '643d69a5c3f7b9001cfa0948',
		name: 'Кристаллы марсианских альфа-сахаридов',
		type: 'main',
		proteins: 234,
		fat: 432,
		carbohydrates: 111,
		calories: 189,
		price: 762,
		image: 'https://code.s3.yandex.net/react/code/core.png',
		image_mobile: 'https://code.s3.yandex.net/react/code/core-mobile.png',
		image_large: 'https://code.s3.yandex.net/react/code/core-large.png',
		__v: 0,
	},
	{
		_id: '643d69a5c3f7b9001cfa0949',
		name: 'Мини-салат Экзо-Плантаго',
		type: 'main',
		proteins: 1,
		fat: 2,
		carbohydrates: 3,
		calories: 6,
		price: 4400,
		image: 'https://code.s3.yandex.net/react/code/salad.png',
		image_mobile: 'https://code.s3.yandex.net/react/code/salad-mobile.png',
		image_large: 'https://code.s3.yandex.net/react/code/salad-large.png',
		__v: 0,
	},
	{
		_id: '643d69a5c3f7b9001cfa094a',
		name: 'Сыр с астероидной плесенью',
		type: 'main',
		proteins: 84,
		fat: 48,
		carbohydrates: 420,
		calories: 3377,
		price: 4142,
		image: 'https://code.s3.yandex.net/react/code/cheese.png',
		image_mobile: 'https://code.s3.yandex.net/react/code/cheese-mobile.png',
		image_large: 'https://code.s3.yandex.net/react/code/cheese-large.png',
		__v: 0,
	},
];
